/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/
SELECT 
  p.product_name,
  SUM(oi.quantity) AS total_quantity,
  ROUND(SUM(oi.quantity * oi.price_per_unit), 1) AS total_sales
FROM order_items oi
LEFT JOIN products p
  ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_sales DESC
LIMIT 10;



/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/
SELECT 
  c.category_name,
  ROUND(SUM(oi.quantity * oi.price_per_unit), 1) AS total_sales,
  (SELECT ROUND(SUM(oi.quantity * oi.price_per_unit), 1) FROM order_items oi) AS overall_sales,
  ROUND( (total_sales / overall_sales)*100, 1) AS pct
FROM order_items oi
LEFT JOIN products p
  ON oi.product_id = p.product_id
LEFT JOIN category c
  ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY total_sales DESC;



/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/
SELECT 
  c.customer_id,
  CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
  ROUND(AVG(oi.quantity * oi.price_per_unit), 1) AS avg_order_value
FROM orders o
LEFT JOIN order_items oi
  ON o.order_id = oi.order_id
LEFT JOIN customers c
  ON o.customer_id = c.customer_id
GROUP BY c.customer_id, customer_name
HAVING COUNT(o.order_id) > 5
ORDER BY avg_order_value DESC;



/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/
WITH demo AS(
            SELECT 
              DATE_FORMAT(o.order_date, 'yyyy-MM') AS month_year,
              ROUND(SUM(oi.quantity * oi.price_per_unit), 1) AS current_month_sales
            FROM orders o
            LEFT JOIN order_items oi
              ON o.order_id = oi.order_id
            WHERE o.order_date >= (SELECT MAX(order_date) - INTERVAL '1 year' FROM orders)
            GROUP BY month_year
            ORDER BY month_year
            )
SELECT 
  *,
  LAG(current_month_sales) OVER (ORDER BY month_year) AS last_month_sales
FROM demo;



/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details
*/

-- Approach 1
SELECT * 
FROM customers c
LEFT JOIN orders o
  ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL
ORDER BY c.customer_id ASC;

-- Approach 2
SELECT * FROM customers
WHERE customer_id NOT IN (SELECT DISTINCT customer_id FROM orders o)
ORDER BY customer_id;


/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/
WITH demo AS (
              SELECT
                cu.state,
                c.category_name,
                ROUND(SUM(oi.quantity * oi.price_per_unit), 1) AS total_sales
              FROM order_items oi
              LEFT JOIN products p
                ON oi.product_id = p.product_id
              LEFT JOIN category c
                ON p.category_id = c.category_id
              LEFT JOIN orders o
                ON oi.order_id = o.order_id
              LEFT JOIN customers cu
                ON o.customer_id = cu.customer_id
              GROUP BY cu.state,c.category_name
              ORDER BY cu.state, total_sales),
demo1 AS (
              SELECT 
                *,
                RANK() OVER(PARTITION BY state ORDER BY total_sales) AS rnk
              FROM demo)
SELECT 
  state,
  category_name,
  total_sales
FROM demo1
WHERE rnk = 1;



/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/
WITH demo AS(
            SELECT 
              c.customer_id,
              CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
              ROUND(SUM(oi.quantity * oi.price_per_unit), 1) AS total_sales
            FROM orders o
            LEFT JOIN order_items oi
              ON o.order_id = oi.order_id
            LEFT JOIN customers c
              ON o.customer_id = c.customer_id
            GROUP BY c.customer_id, customer_name
            ORDER BY total_sales DESC)
SELECT 
  customer_name,
  total_sales,
  RANK() OVER(ORDER BY total_sales DESC) AS rnk
FROM demo;


/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/
WITH demo AS(
            SELECT
              product_id,
              MAX(last_stock_date) AS max_stock_date
            FROM inventory
            GROUP BY product_id)
SELECT 
  p.product_name,
  i.stock,
  i.warehouse_id,
  i.last_stock_date
FROM inventory i
JOIN demo d
  ON i.product_id = d.product_id AND i.last_stock_date = d.max_stock_date
JOIN products p
  ON i.product_id = p.product_id
WHERE stock < 10;




/*
9. Shipping Delays
Identify orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/

SELECT 
  CONCAT( c.first_name,' ', c.last_name) AS customer_name,
  o.order_id,
  o.order_date,
  s.shipping_date,
  DATEDIFF(s.shipping_date, o.order_date) AS shipping_days,
  s.shipping_providers
FROM orders o
LEFT JOIN shipping s
  ON o.order_id = s.order_id
LEFT JOIN customers c
  ON o.customer_id = c.customer_id
WHERE DATEDIFF(s.shipping_date, o.order_date) > 3;


/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/
SELECT 
  payment_status,
  COUNT(order_id) AS total_orders,
  (SELECT COUNT(order_id) FROM payments) AS overall,
  ROUND( (total_orders / overall) * 100, 1) AS pct
FROM payments
GROUP BY payment_status;


/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/
SELECT
s.seller_id,
s.seller_name,
ROUND( SUM(oi.quantity * oi.price_per_unit), 1) AS total_sales,
COUNT(CASE WHEN o.order_status = 'Completed' THEN o.order_id END) AS completed_orders,
COUNT(CASE WHEN o.order_status = 'Cancelled' THEN o.order_id END) AS cancelled_orders,
ROUND( (completed_orders / COUNT(o.order_id)) * 100, 1) AS completed_pct
 FROM orders o
LEFT JOIN sellers s
  ON o.seller_id = s.seller_id
LEFT JOIN order_items oi
  ON o.order_id = oi.order_id
WHERE o.order_status IN ('Completed', 'Cancelled')
GROUP BY s.seller_id, s.seller_name
ORDER BY total_sales DESC
LIMIT 5;



/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/
WITH demo AS (
              SELECT 
                p.product_name,
                ROUND( SUM(oi.quantity * oi.price_per_unit), 1) AS total_revenue,
                ROUND( SUM(oi.quantity * p.cogs), 1) AS total_cost,
                ROUND( ((total_revenue - total_cost) / total_revenue) * 100, 1 ) AS profit_pct
              FROM order_items oi
              LEFT JOIN products p
                ON oi.product_id = p.product_id
              GROUP BY p.product_name
              ORDER BY profit_pct DESC)
SELECT 
  *,
  DENSE_RANK() OVER(ORDER BY profit_pct DESC) AS rnk
FROM demo;

/*
13. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/
SELECT 
  p.product_name,
  SUM(CASE WHEN o.order_status IN ('Inprogress', 'Completed') THEN oi.quantity END) AS total_sold,
  SUM(CASE WHEN o.order_status = 'Returned' THEN oi.quantity END) AS total_returned,
  ROUND( (total_returned / total_sold) * 100, 1) AS return_rate
FROM orders o
LEFT JOIN order_items oi
  ON o.order_id = oi.order_id
LEFT JOIN products p
  ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_returned DESC
LIMIT 10;


/*
14. Orders Pending Shipment
Find orders that have been paid but are still pending shipment.
Challenge: Include order details, payment date, and customer information.
*/

SELECT 
  o.order_id,
  o.order_date,
  p.payment_date,
  CONCAT(c.first_name,' ', c.last_name) AS customer_name
FROM orders o
LEFT JOIN payments p
  ON o.order_id = p.order_id
LEFT JOIN shipping s
  ON o.order_id = s.order_id
LEFT JOIN customers c
  ON o.customer_id = c.customer_id
WHERE p.payment_status = 'Payment Successed' AND delivery_status = 'Shipped';


/*
15. Inactive Sellers
Identify sellers who haven’t made any sales in the last 6 months.
Challenge: Show the last sale date and total sales from those sellers.
'2025-01-01' - Use this date as the max date
*/
WITH demo AS (
              SELECT * 
              FROM sellers
              WHERE seller_id NOT IN (
                            SELECT 
                              seller_id 
                            FROM orders
                            WHERE order_date >= '2025-01-01' - INTERVAL 180 DAY)
              )
SELECT 
  d.seller_id, 
  d.seller_name, 
  d.origin,
  MAX(o.order_date) AS last_sale_date
FROM demo d
JOIN orders o
  ON d.seller_id = o.seller_id
GROUP BY d.seller_id, d.seller_name, d.origin;



/*
16. IDENTITY customers into returning or new
if the customer has done more than 5 return categorize them as returning otherwise new
Challenge: List customers id, name, total orders, total returns
*/
SELECT 
  c.customer_id,
  CONCAT(c.first_name,' ', c.last_name) AS customer_name,
  COUNT(DISTINCT o.order_id) AS total_orders,
  COUNT(DISTINCT CASE WHEN o.order_status = 'Returned' THEN o.order_id END) AS total_returns,
  (CASE WHEN total_returns > 5 THEN 'Returning' ELSE 'New' END) AS customer_type
FROM orders o
LEFT JOIN customers c
  ON o.customer_id = c.customer_id
GROUP BY c.customer_id, customer_name
ORDER BY c.customer_id;

/*
17. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders for each customer.
*/
WITH demo AS (
              SELECT
                c.state,
                CONCAT(c.first_name,' ', c.last_name) AS customer_name,
                COUNT(DISTINCT o.order_id) AS total_orders
              FROM orders o
              LEFT JOIN customers c
                ON o.customer_id = c.customer_id
              GROUP BY c.state, customer_name
              ORDER BY c.state, total_orders DESC),
demo1 AS (
          SELECT 
            *,
            ROW_NUMBER() OVER(PARTITION BY state ORDER BY total_orders DESC, customer_name) AS rnk
          FROM demo)
SELECT 
  state,
  customer_name,
  total_orders
FROM demo1
WHERE rnk <= 5;



/*
18. Revenue by Shipping Provider
Calculate the total revenue handled by each shipping provider.
Challenge: Include the total number of orders handled and the average delivery time for each provider.
*/
SELECT 
  s.shipping_providers,
  ROUND( SUM(oi.quantity * oi.price_per_unit), 1) AS total_revenue,
  COUNT(o.order_id) AS total_orders,
  ROUND(AVG(DATEDIFF(s.shipping_date, o.order_date)),1) AS avg_delivery_time
FROM orders o
JOIN order_items oi
  ON oi.order_id = o.order_id
JOIN shipping s
  ON o.order_id = s.order_id
JOIN products p
  ON oi.product_id = p.product_id
GROUP BY s.shipping_providers;




/*
19. Top 10 product with highest decreasing revenue ratio compare to last year(2022) and current_year(2023)
Challenge: Return product_id, product_name, category_name, 2022 revenue and 2023 revenue decrease ratio at end Round the result

Note: Decrease ratio = cr-ls/ls* 100 (cs = current_year ls=last_year)
*/
SELECT 
  p.product_id,
  p.product_name,
  c.category_name,
  ROUND(SUM(CASE WHEN YEAR(o.order_date) = 2022 THEN (oi.quantity * oi.price_per_unit) END),1) AS last_year_sales,
  ROUND(SUM(CASE WHEN YEAR(o.order_date) = 2023 THEN (oi.quantity * oi.price_per_unit) END),1) AS current_year_sales,
  ROUND( (((current_year_sales - last_year_sales) / last_year_sales) * 100), 1) AS yoy_growth
FROM order_items oi
LEFT JOIN orders o
  ON oi.order_id = o.order_id
LEFT JOIN products p
  ON oi.product_id = p.product_id
LEFT JOIN category c
  ON p.category_id = c.category_id
GROUP BY p.product_id, p.product_name, c.category_name
HAVING yoy_growth IS NOT NULL
ORDER BY yoy_growth
LIMIT 10;









